services:
  admin:
    build: .
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/flexiq_db"
    ports:
      - "8080:8080"
  postgres:
    image: postgres:18.1-alpine
    container_name: flexiq-postgres
    environment:
      POSTGRES_DB: flexiq_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: